### ISSUE TITLE
Panic on tilling window manager

### ISSUE THREAD

**Issue by FloVanGH** [emoon/rust_minifb#105] opened 2019-11-25 06:00 UTC
Some users of OrbTk reported a crash of the examples on tilling window mangers: https://gitlab.redox-os.org/redox-os/orbtk/issues/195#note_18953

**Comment by emoon** [comment] 2019-11-28 12:37
Thanks for the report. I will take a look next week

**Comment by emoon** [comment] 2019-12-02 16:02
I tried this on Linux and i3 window manager (noise example) and I'm not able to reproduce the crash. Is there some more info on this what is required for this to fail?

**Comment by edge90** [comment] 2019-12-03 07:06
The crash occurred on a normal gnome desktop as well. Looked like it was the resize event that caused it. My tiling wm (sway) created a small window then resized it to be larger than some buffer.

**Comment by emoon** [comment] 2019-12-03 11:14
And does this happen on a specific example in minifb as well? (like the noise one)

**Comment by stevensonmt** [comment] 2019-12-04 05:05
```
>> cargo run --example multi --release
warning: unused manifest key: package.maintenance
    Finished release [optimized] target(s) in 0.09s
     Running `target/release/examples/multi`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UpdateFailed("Update failed because input buffer is too small. Required size for 661 x 348 window (1x scale) is 920112 bytes but the size of the input buffer has the size 819200 bytes")', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
WM: leftwm 0.1.10
minifb: 0.13

Of note, the noise example works fine.

**Comment by emoon** [comment] 2019-12-04 08:09
Cool. Thanks for the report. I'm going to work on this today

**Comment by emoon** [comment] 2019-12-04 14:11
So update on this and how I will fix it is in https://github.com/emoon/rust_minifb/issues/105

**Comment by FloVanGH** [comment] 2019-12-05 12:57
It works now if I ignore the the result error of `update_with_buffer_size`. It's the same error message as before. And during the resize you could see sometimes the same visual effect, almost by downsize.

**Comment by emoon** [comment] 2019-12-06 08:16
Cool. Yeah I'm currently working on fixing all of the resizing issues. I will add some extra options to `WindowOpts` that allow you to set how the resizing should work (as it's different depending on your application)

**Comment by emoon** [comment] 2019-12-07 09:03
@stevensonmt hey, if you have the possibility of grabbing the latest minifb, switch over to `dev` branch and try this again that would be awesome. I hope it should all be fixed now.

**Comment by stevensonmt** [comment] 2019-12-07 16:00
@emoon,
Can confirm fixed on dev branch. Thanks for your work on this!

**Comment by emoon** [comment] 2019-12-07 16:16
Awesome! Thanks for checking :)

**Comment by FloVanGH** [comment] 2019-12-07 19:42
@emoon I can confirm that to. Thank you :-)

**Comment by emoon** [comment] 2019-12-07 19:49
Thanks! Moving over to doing mac fixes now

**Comment by emoon** [comment] 2019-12-16 07:26
Closing this now as `0.15` has been released with the fixes for this

**Closed by emoon** 2019-12-16 07:26 UTC
Labels: bug
