### ISSUE TITLE
Failed to create server-side surface decoration: Missing

### ISSUE THREAD

**Issue by brsvh** [emoon/rust_minifb#205] opened 2020-08-13 15:17 UTC
I try to build the _noise_ example on my computer, I get some error like this. 

```
Failed to create server-side surface decoration: Missing
thread 'main' panicked at 'not implemented', src/os/posix/mod.rs:227:40
```

I'm sure I have installed `libxkbcommon-devel`, `libwayland-cursor0`, `wayland-devel` and `libwayland-client0`.

**OS info**

distribution: openSUSE Tumbleweed
arch: x86_64
wayland version: 1.18.0
libxkbcommon version: 0.10.0

**Build log**

```
   Compiling libc v0.2.74
   Compiling pkg-config v0.3.18
   Compiling proc-macro2 v1.0.19
   Compiling unicode-xid v0.2.1
   Compiling cfg-if v0.1.10
   Compiling bitflags v1.2.1
   Compiling xml-rs v0.8.3
   Compiling nix v0.17.0
   Compiling getrandom v0.1.14
   Compiling void v1.0.2
   Compiling version_check v0.9.2
   Compiling semver-parser v0.7.0
   Compiling memchr v2.3.3
   Compiling once_cell v1.4.0
   Compiling smallvec v1.4.2
   Compiling downcast-rs v1.2.0
   Compiling maybe-uninit v2.0.0
   Compiling ppv-lite86 v0.2.8
   Compiling cc v1.0.58
   Compiling remove_dir_all v0.5.3
   Compiling lazy_static v1.4.0
   Compiling semver v0.9.0
   Compiling nom v5.1.2
   Compiling rustc_version v0.2.3
   Compiling wayland-sys v0.27.0
   Compiling xkbcommon-sys v0.7.4
   Compiling x11-dl v2.18.5
   Compiling cast v0.2.3
   Compiling quote v1.0.7
   Compiling wayland-scanner v0.27.0
   Compiling minifb v0.17.0 (/home/brs/projects/rust_minifb)
   Compiling raw-window-handle v0.3.3
   Compiling rand_core v0.5.1
   Compiling xkb v0.2.1
   Compiling rand_chacha v0.2.2
   Compiling rand v0.7.3
   Compiling wayland-client v0.27.0
   Compiling wayland-protocols v0.27.0
   Compiling xcursor v0.3.2
   Compiling tempfile v3.1.0
   Compiling wayland-commons v0.27.0
   Compiling wayland-cursor v0.27.0
    Finished dev [unoptimized + debuginfo] target(s) in 19.56s
   Compiling byteorder v1.3.4
   Compiling crc32fast v1.2.0
   Compiling adler32 v1.2.0
   Compiling minifb v0.17.0 (/home/brs/projects/rust_minifb)
   Compiling miniz_oxide v0.3.7
   Compiling deflate v0.8.6
   Compiling png v0.16.7
    Finished dev [unoptimized + debuginfo] target(s) in 3.36s
     Running `target/debug/examples/noise`
Failed to create server-side surface decoration: Missing
thread 'main' panicked at 'not implemented', src/os/posix/mod.rs:227:40
stack backtrace:
   0:     0x562754bd6205 - backtrace::backtrace::libunwind::trace::ha215bbf14e328799
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x562754bd6205 - backtrace::backtrace::trace_unsynchronized::h3384b099b135857a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x562754bd6205 - std::sys_common::backtrace::_print_fmt::hfec93740f7294682
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x562754bd6205 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5fe20777f4174074
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x562754bf596c - core::fmt::write::he14c3177144df275
                               at src/libcore/fmt/mod.rs:1076
   5:     0x562754bd3be3 - std::io::Write::write_fmt::h8e26323bfab8bcc5
                               at src/libstd/io/mod.rs:1537
   6:     0x562754bd8810 - std::sys_common::backtrace::_print::h9cfa4c87526ba064
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x562754bd8810 - std::sys_common::backtrace::print::h94936584848b3272
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x562754bd8810 - std::panicking::default_hook::{{closure}}::h733b20cc9b496e46
                               at src/libstd/panicking.rs:198
   9:     0x562754bd855c - std::panicking::default_hook::h556d8cff6c12a651
                               at src/libstd/panicking.rs:218
  10:     0x562754bd8e47 - std::panicking::rust_panic_with_hook::ha0c7ca5b39baa9d5
                               at src/libstd/panicking.rs:486
  11:     0x562754b1edc9 - std::panicking::begin_panic::hf7c950f7c8bc5a41
                               at /home/brs/.local/share/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:410
  12:     0x562754a2575f - minifb::os::posix::Window::get_keys_released::h04c32028b3925d4d
                               at src/os/posix/mod.rs:227
  13:     0x562754a23457 - minifb::Window::get_keys_released::h138c01520d58c9f4
                               at /home/brs/projects/rust_minifb/src/lib.rs:597
  14:     0x562754a24dd1 - noise::main::h21b7e3b8ffd54373
                               at examples/noise.rs:59
  15:     0x562754a23c0b - std::rt::lang_start::{{closure}}::hf4dfaf85dea28bbc
                               at /home/brs/.local/share/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  16:     0x562754bd9218 - std::rt::lang_start_internal::{{closure}}::hefb489d56a389b75
                               at src/libstd/rt.rs:52
  17:     0x562754bd9218 - std::panicking::try::do_call::hb2bfa58b743656f1
                               at src/libstd/panicking.rs:297
  18:     0x562754bd9218 - std::panicking::try::haaa85a89ce3784c3
                               at src/libstd/panicking.rs:274
  19:     0x562754bd9218 - std::panic::catch_unwind::h49baa277f74e60cb
                               at src/libstd/panic.rs:394
  20:     0x562754bd9218 - std::rt::lang_start_internal::h7aa2f6739b31fe58
                               at src/libstd/rt.rs:51
  21:     0x562754a23be7 - std::rt::lang_start::hfb3ac83d4569ced1
                               at /home/brs/.local/share/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  22:     0x562754a24eda - main
  23:     0x7f27985decca - __libc_start_main
  24:     0x562754a231aa - _start
                               at ../sysdeps/x86_64/start.S:120
  25:                0x0 - <unknown>

```

**Comment by emoon** [comment] 2020-08-13 18:08
Hey,

Ok it seems to be caused by this:

https://github.com/emoon/rust_minifb/blame/master/src/os/posix/mod.rs#L227

So if you temporary comment out this block of code in `noise.rs`

https://github.com/emoon/rust_minifb/blob/master/examples/noise.rs#L59-L67

It should hopefully work until this gets fixed

**Comment by emoon** [comment] 2020-08-13 18:16
I have pushed a (hopefully) fix for this, if you can try with latest git version and see if it solves the issue.

**Comment by brsvh** [comment] 2020-08-14 00:02
thx, it works fine.

**Closed** 2020-08-14 00:02 UTC

**Comment by emoon** [comment] 2020-08-14 03:43
Great! I will release an updated version later today

**Comment by emoon** [comment] 2020-08-14 09:59
@brsvh 0.18 has now been released so you can switch to that one if you wish
