### ISSUE TITLE
Blurry on Retina Display on macOS

### ISSUE THREAD

**Issue by yurivish** [emoon/rust_minifb#30] opened 2016-10-25 04:36 UTC
Hi!

This library looks fantastic. I was just playing with it and noticed there's a blur when used on a Retina Macbook Pro (mid-2012) – do you have an idea why?

My scaling setting is set to X1, and here's what a screenshot looks like of a black screen with a single pixel set to white:

<img width="312" alt="screenshot 2016-10-25 00 34 17" src="https://cloud.githubusercontent.com/assets/114388/19673121/ef9305c8-9a4a-11e6-8593-8e55dda8571e.png">

And here it is again zoomed in:

![screenshot 2016-10-25 00 36 11](https://cloud.githubusercontent.com/assets/114388/19673126/09ebd85a-9a4b-11e6-8acd-7ab59571ce57.png)

You can see little 'wings' off to each of the four sides. Is this intentional, or a bug?

**Comment by emoon** [comment] 2016-10-25 04:46
Hi,

Thank for the report.

This isn't expected but I'm not sure where the issue actually is I would guess it could be caused by 3 things.

1. The display area (where the pixels are set) isn't correctly calculated and have "off by one" error (meaning that a 320x200 area might be 319x199 or similar) that would cause some slight scaling of the image.
2. The code here https://github.com/emoon/rust_minifb/blob/master/src/native/macosx/OSXWindowFrameView.m#L25 always some some kind of filtering which should be disabled.
3. I'm unsure of exactly how retina will affect single pixels like this as Retina will essentially "scale" the screen. Do you think you can try to disable Retina (go to 1:1 mode) and see if the issue is still there?

**Comment by yurivish** [comment] 2016-10-25 05:11
Hey! Thanks for the quick response.

It's gone if I switch to 2880x1800:

![screenshot 2016-10-25 01 10 44](https://cloud.githubusercontent.com/assets/114388/19673664/eb1f8a16-9a4f-11e6-84f1-c30484a33681.png)

**Comment by yurivish** [comment] 2016-10-25 05:12
(that's a big square, not a single pixel; I wrote a little function to draw squares... but they're still blurry at my usual resolution)

**Comment by floooh** [comment] 2016-10-25 07:02
I've seen similar behaviour in my own 3D engine (noticeable with text rendering which I never could get crisp) and also in browsers before, the reason there was that the CALayer class default to linear filtering when composing the layer image in the window system.

See CALayer and search for 'filter' (there are several properties, but the one that made the difference was the magnificationFilter).

For instance in my code, I'm getting the layer from an MTKView object, and set the magnification filter, this fixed the blurriness:
```
[[bridge->mtkView layer] setMagnificationFilter:kCAFilterNearest];
```

Here's the related browser bug for Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=602103

Hope this helps :)

**Comment by emoon** [comment] 2016-10-25 07:16
Thanks! I will see if I can apply something similar to my code.

**Comment by emoon** [comment] 2018-10-23 18:58
Hi, I have rewritten the macOS support to use Metal instead. I haven't looked in detail on this issue but let me know if it helps out. I will close this for now but if it doesn't work correctly please re-open it again.

**Closed by emoon** 2018-10-23 18:58 UTC
Labels: bug, macOS
