### ISSUE TITLE
Any way to mutablly borrow the internal buffer directly ?

### ISSUE THREAD

**Issue by 38** [emoon/rust_minifb#97] opened 2019-11-01 21:45 UTC
Hi there, thanks for the amazing crate.  `mini_fb` is awesome and  I really like the simple API and minimal dependencies. 

Currently it seems we don't have a good way to avoid copy the buffer, since the API just allow developer provide a reference to an external buffer. And mini_fb will copy the external buffer to the internal one. 
So I am wondering is there any way to directly borrow the internal buffer and manipulate it with external code ? Is there any chance to improve the performance by doing this ?

Thanks in advance!

**Comment by emoon** [comment] 2019-11-02 08:13
Hi, Thanks for the appreciation :)

So there are some reasons why the API is like this but the main one is threading and life times.

1. Threading: A user may generate the buffer on a different thread than the main thread that minifb is running on. This would make things much more complicated to support as another thread would need to borrow something mutable from the main thread which is illegal in minifb.
2. How the backend API works for each platform varies. On macOS the buffer will be uploaded to the GPU at a point when a certain event comes to the application. This would mean there are potential problems if the user may changing the buffer while minifb needs to read from it.
3. A user may chose to only update a part of the buffer for minifb (a slice) if the display area is bigger (say scrolling up and down where you need extra memory on the "sides") if only using borrowing this would mean that the user would have to copy into the buffer by them self.
4. memcpy is usually implemented in an efficient way on most platforms as it's a common operation so I haven't seen that much issue with it in practice. That being said if it takes much time it's possible to leave the main thread only dealing with minifb and have another thread (as stated in 1) doing all the generation of the buffer.

I hope this explains the reasoning behind the current API.

Cheers!

**Comment by 38** [comment] 2019-11-03 00:07
Thanks for the explain. 

I can understand why this is tricky, but it still seems doable to me. I am just curious if there's a plan for avoiding copy at least in some use cases. (I will explain the background later). 

For the reason of copying data, i sort of agree and disagree with.

1. For threading, I know it's tricky to make a borrow. I would image an `Arc` based token do the trick to address the lifetime and if we add a wrapper which packs an Arc and some additional information (plus we can also make sure that the Arc isn't cloned if it's hidden behind our wrapper), when the render thread is done, just simply send the token back to the main thread would do the thing. At least I feel this is solvable problem.
2. For platform difference, I am sort of disagree, since even if on some platform it's impossible to avoid copy, but this is not a reason for copying data on a platform where this is possible (such as Linux).  
3. For the partial update. Same to 2, it doesn't means we should disallow borrowing even for a full update.
4. Memcpy is efficient, but it's not free, just wondering if we can do better. Plus the cost is related to the size of the buffer (especially image buffer isn't a small one). 

I maintains a plotting library called `plotters`, in my issue list, people mentioned the combination of `mini_fb` and `plotters` for real-time data visualization a few times that sounds really interesting to me.

In my issue list,  people who want to have realtime display do really care about the performance a lot. (Not only FPS but CPU load matters) That's why I am thinking about if we can avoid copy in the entire process and this sounds a good story (Plus incremental drawing with plotters).

So I am thinking about provide built-in support for `mini_fb` in some really efficient way. 

Finally, I am really appreciate you detailed explain, but I am still imagine this feature would be cool for me.

Thanks!

**Comment by emoon** [comment] 2019-11-03 07:44
`Arc<>` would not give mutability and you need something like `RefCell` or such as well. It will be kinda annoying when doing threading. Also Linux will soon have the same issue as `macOS` as I'm adding (optional) support for OpenGL as it's a lot faster.

I can put it on my list of things to look at but it's growing to see if it would work on most platforms without causing issues but I don't think I'm going to implement it for a while at least.

Cheers!

**Comment by emoon** [comment] 2019-12-06 08:33
So another problem  has turned up. Some Window managers on Linux will force a certain widow size (even if you set the window to a fixed size) So the problem is then that the user will expect the buffer to be 256x256 it may end up being 643x245 because that is what the window manager has decided. I really don't want the user to have to deal with that but should be able to render in 256x256 and minifb deals with resizing/poisoning/etc

What I will try is to skip the extra memcpy when possible (so just add it to the GPU queue on such platforms) when the sizes matches up (which will be the majority of the cases) but to give access to the internal buffer won't work due to this.

**Comment by emoon** [comment] 2019-12-06 13:08
Closing this one now in favour of trying to skip internal memcpys when possible

**Closed by emoon** 2019-12-06 13:08 UTC

**Comment by emoon** [comment] 2019-12-14 12:28
Just FYI I have removed the internal memcpy on all platforms on the `dev` branch (will be part of 0.15)

**Comment by J-Cake** [comment] 2023-09-28 09:56
If I may ask whether solutions like double-buffering have been considered? IMO this would address most of the issues mentioned, including the issue of the buffer changing arbitrarily. As acquiring a mutable reference to the buffer is not the primary intended usage method, it could be stated clearly in the documentation that this should be considered. Since Rust enforces single-mutable-borrower patterns, if the internal structure of the buffer is sound, then this carries out to users. If the back buffer holds a lock when it is not in use, calls to `get_buffer_mut()` would lock it etc. Calling `update*` would automatically acquire a lock on the back buffer and swap them. 

Perhaps my youthful naivité is blinding me here, but this at least _sounds_ reasonable to me

**Comment by emoon** [comment] 2023-09-28 10:25
I honestly don't think it's worth the added extra complexity to implement this.

**Comment by J-Cake** [comment] 2023-09-28 10:38
That's disappointing but understandable as it is quite an involved upgrade. Perhaps if there were a way to delegate this to third-party crates, this might be feasible?

**Comment by emoon** [comment] 2023-09-28 10:41
As this is an internal implementation detail for all the backends (windows, macos, linux, etc) I don't think so

**Comment by J-Cake** [comment] 2023-09-28 10:43
understood. well regardless, it's a wonderful little crate which often gets me off the ground immensely quickly

**Comment by emoon** [comment] 2023-09-28 10:45
Thanks! :)
